pipeline {
    agent any
    stages {
        stage('Clean Up') {
            steps {
                deleteDir()
            }
        }
        stage('Clone Repo') {
            steps {
                bat 'git clone https://github.com/Mounika77754/simple-java-maven-app.git'
            }
        }
        stage('Update Java Requirement') {
            steps {
                dir('simple-java-maven-app') {
                    powershell '''(Get-Content pom.xml) -replace "\\[21,\\)", "[17,)" | Set-Content pom.xml'''
                }
            }
        }
        stage('Build') {
            steps {
                dir('simple-java-maven-app') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Test') {
            steps {
                dir('simple-java-maven-app') {
                    bat 'mvn test'
                }
            }
        }
    }
}
